#!/bin/bash

#Setup Script

apt update -y

apt upgrade -y

apt-get install -y libbsd-dev

apt install python3 -y

apt install python-pip -y

apt-get install pylint

apt install unzip

chmod +x bedrock

apt install gcc